language:python
python:
      - 2.7
before_install:
      - wget http://peak.telecommunity.com/dist/ez_setup.py python ez_setup.py
      - wget http://python-distribute.org/distribute_setup.py python distribute_setup.py
      - wget https://github.com/pypa/pip/raw/master/contrib/get-pip.py python get-pip.py
install:
      - pip install tornado

script:
      - python test.py
      - python toranado_example.py
