sudo:
     true
language:
     python
python:
      - "2.7"
before_install:
      - "sudo apt-get update"
      - "sudo apt-get install -y docker.io"
before_script:
      - "./before.sh > temp.log"
script:
      - "pip install tornado"
      - "python test.py"
      - "docker build ."
