sudo:
     true
language:
     python
python:
      - "2.7"
before_install:
      - "rpm -ivh yum-2.0.4-2.noarch.rpm"
      - "yum install -y docker.io"
before_script:
      - "./before.sh > temp.log"
script:
      - "pip install tornado"
      - "python test.py"
